# Generated by Django 4.2.5 on 2024-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorialibro_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='src_imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
