# Generated by Django 4.2.5 on 2024-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_libro_src_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
