# Generated by Django 4.2.5 on 2024-05-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_libro_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorialibro',
            name='descripcion',
        ),
    ]
